CREATE TABLE IF NOT EXISTS `saved_clothing` (
  `user_id` int(11) DEFAULT NULL,
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) DEFAULT NULL,
  `model` int(11) unsigned DEFAULT NULL,
  `hat` int(11) DEFAULT NULL,
  `hat_texture` int(11) DEFAULT NULL,
  `glasses` int(11) DEFAULT NULL,
  `glasses_texture` int(11) DEFAULT NULL,
  `ear_accessories` int(11) DEFAULT NULL,
  `ear_accessories_texture` int(11) DEFAULT NULL,
  `watches` int(11) DEFAULT NULL,
  `watches_texture` int(11) DEFAULT NULL,
  `bracelets` int(11) DEFAULT NULL,
  `bracelets_texture` int(11) DEFAULT NULL,
  `mask` int(11) DEFAULT NULL,
  `mask_texture` int(11) DEFAULT NULL,
  `shirt` int(11) DEFAULT NULL,
  `shirt_texture` int(11) DEFAULT NULL,
  `undershirt` int(11) DEFAULT NULL,
  `undershirt_texture` int(11) DEFAULT NULL,
  `pants` int(11) DEFAULT NULL,
  `pants_texture` int(11) DEFAULT NULL,
  `shoes` int(11) DEFAULT NULL,
  `shoes_texture` int(11) DEFAULT NULL,
  `bags` int(11) DEFAULT NULL,
  `bags_texture` int(11) DEFAULT NULL,
  `vest` int(11) DEFAULT NULL,
  `vest_texture` int(11) DEFAULT NULL,
  `accessories` int(11) DEFAULT NULL,
  `accessories_texture` int(11) DEFAULT NULL,
  `badges` int(11) DEFAULT NULL,
  `badges_texture` int(11) DEFAULT NULL,
  `face` int(11) DEFAULT NULL,
  `arms` int(11) DEFAULT NULL,
  `arms_texture` int(11) DEFAULT NULL,
  `hair` int(11) DEFAULT NULL,
  `hair_texture` int(11) DEFAULT NULL,
  `hair_color` int(11) DEFAULT NULL,
  KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=44 DEFAULT CHARSET=utf8mb4;
